### ISSUE TITLE
Empty album name gives an URL error

### ISSUE THREAD

**Issue by empiremaya33** [bloha/rajce-dl#4]
If album name is empty for some reason, it gives an URL error and breaks the download of other albums.

Empty album name URL in Rajce is ending to two slashes: https://[censored].rajce.idnes.cz//

After checking does that album exist in Rajce, it doesn't, but it was listed in the user's album list (bug in Rajce?)

Error log:

```
Traceback (most recent call last):
  File "/usr/local/bin/rajce-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/cli/command_line_interface.py", line 49, in main
    CommandLineInterface().run()
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/cli/command_line_interface.py", line 45, in run
    self.__state_manager.execute(states)
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/state/state_manager.py", line 21, in execute
    for sub_state in state.sub_states:
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/state/generator/albums_download_states_generator.py", line 20, in __next__
    self.__next_states = self._get_next_states()
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/state/generator/api_based_albums_download_states_generator.py", line 30, in _get_next_states
    return [self._create_state(AlbumLocation(data['url'])) for data in data_list]
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/state/generator/api_based_albums_download_states_generator.py", line 30, in <listcomp>
    return [self._create_state(AlbumLocation(data['url'])) for data in data_list]
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/location/album_location.py", line 14, in __init__
    super().__init__(raw_url)
  File "/usr/local/lib/python3.8/dist-packages/rajce_dl/location/rajce_location.py", line 10, in __init__
    raise ValueError(f'URL: {raw_url} is invalid.')
ValueError: URL: //[censored].rajce.idnes.cz// is invalid.
```

**Comment by bloha** [comment]
> After checking does that album exist in Rajce, it doesn't, but it was listed in the user's album list (bug in Rajce?)

Is that album is accessible from the rajce website?

**Comment by empiremaya33** [comment]
> Is that album is accessible from the rajce website?

No, the album gave 404 not found on the website. It doesn't give problems anymore in the latest rajce-dl version.
